version: "3"

services:
  goserversaml:
    image: goserversaml:latest
    ports:
      - "8002:8002"
    networks:
      - private-net
      - public-net
  goserver-redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - private-net
  goserver:
    image: goserver:latest
    depends_on:
      - "goserversaml"
      - "goserver-redis"
    ports:
      - "8001:8001"
    networks:
      - private-net
      - public-net
  osquery-ubuntu18:
    image: osquerydist:latest
    deploy:
        replicas: 2
    depends_on:
      - "goserver"
    build:
      context: .
      dockerfile: "docker/nodes/ubuntu18/Dockerfile"
    networks:
      - private-net
networks:
  public-net:
  private-net:
